[menu]
title = "BI Pharma Mali"
orientation = "horizontal"

[client]
# DÃ©sactive la navigation automatique du dossier pages
showSidebarNavigation = false

[browser]
gatherUsageStats = true

[[menu.pages]]
name = "Refactoring"
icon = "âš™ï¸"
file = "pages.refactoring"

[[menu.pages]]
name = "Analyse"
icon = "ğŸ“Š"
file = "pages.analyse"

[[menu.pages]]
name = "Stocks"
icon = "ğŸ“¦"
file = "pages.stocks"


[server]
runOnSave = true
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501